<?php

# The Public Whip, Copyright (C) 2003 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.
?>

</div><!-- end main content -->
</div><!-- end whitebox-->
<div id="bluebox">
    <div class="widewidth">
        <div class="col1-2"><h3>About the Project</h3>

            <p>The Public Whip is a not-for-profit, open source website created in 2003 by Francis Irving and Julian
                Todd and now run by <a href="https://www.bairwell.com">Bairwell Ltd</a>.</p>

            <p>PublicWhip <a href="https://github.com/publicwhip/publicwhipv2">v2 codebase</a> is currently under development - you can join the <a href="https://join.slack.com/t/publicwhip/shared_invite/enQtNTczMTg1MTc1Mzc3LTAxMjkyYzNhNWY0NDdmY2EzYjYwNTZjNjQ1YTNiOTQwZWYzM2Q0ZDJjOWU5MTVjNzZmNGFjMzljY2U0ZjA0YjM">Slack group</a> to find out more or email
                team@publicwhip.org.uk</p></div>
        <div class="col3"><h3>The Whip on the Web</h3>
            <ul class="social">
                <li class="tw"><a href="https://twitter.com/publicwhip">Twitter</a></li>
                <li class="fb"><a href="https://www.facebook.com/pages/Public-Whip/199268083464697">Facebook</a></li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    <?php
    if (true===function_exists('advertisement')) {
    advertisement('footer');
    }
    ?>
</div><!--end bluebox-->
<div id="footer">
    <div class="widewidth">
        <!-- the footer section -->
        <!-- old footer links <a title="Frequently asked questions" href="/faq.php#whatis">About us</a>
<a title="Send comments, problems or suggestions" href="/email.php">Contact us</a>
<a title="Fodder for your spreadsheet" href="/project/data.php">Data feeds</a>
<a title="Public Whip is open source software" href="/project/code.php">Source code</a>
<a title="Divisions in your news reader" href="/faq.php#rss">RSS</a>
<a title="Details on the free license for this data" href="/faq.php#legal">Legal information</a>-->
        <div class="legal">&copy; 2018 Bairwell Ltd. The Public Whip is a not-for-profit, open source, project. Get the
            <a href="https://github.com/publicwhip/publicwhip">source code on Github</a>.<br>
            Questions/problems? Please email <a href="mailto:team@publicwhip.org.uk">team@publicwhip.org.uk</a><br>
            Maintained and supported by <a href="https://www.bairwell.com">Bairwell Ltd PHP/Node.JS development</a>.<br>
        </div>
    </div>
    <div class="clear"></div>
</div><!-- end footer-->
</body>
</html>
